#!/system/bin/sh
# Script to start "hello" on the device, which has a very rudimentary
# shell.
#
base=/system
export CLASSPATH=$base/framework/hello.jar
exec app_process $base/bin com.sj.commands.hello.Hello "$@"
